 export const unitdata = [
  { id: 1, title: "Introduction to Python", pages: ["Page 1: History of Python", "Page 2: Setting up Environment", "Page 3: Interpreted vs Compiled", "Page 4: Syntax Basics", "Page 5: Indentation Rules", "Page 6: Python Applications"], quiz: "Is Python a compiled language?", assignment: "Install Python and print 'Hello World'" },
  { id: 2, title: "Variables & Data Types", pages: ["Page 1: Naming variables", "Page 2: Integer & Float", "Page 3: Strings basics", "Page 4: Boolean types", "Page 5: Type conversion", "Page 6: Memory basics"], quiz: "How to check data type?", assignment: "Store and print user details" },
  { id: 3, title: "Operators", pages: ["Page 1: Arithmetic", "Page 2: Comparison", "Page 3: Logical", "Page 4: Bitwise", "Page 5: Assignment", "Page 6: Membership"], quiz: "What is the 'in' operator?", assignment: "Calculator script" },
  { id: 4, title: "Control Flow: If/Else", pages: ["Page 1: If statements", "Page 2: Else & Elif", "Page 3: Nested Ifs", "Page 4: Logical Operators", "Page 5: Short-circuiting", "Page 6: Truthy values"], quiz: "How to write elif?", assignment: "Grade calculator" },
  { id: 5, title: "Loops: For/While", pages: ["Page 1: For loops", "Page 2: While loops", "Page 3: Range function", "Page 4: Break statement", "Page 5: Continue statement", "Page 6: Nested loops"], quiz: "How to exit a loop?", assignment: "Print table of 5" },
  { id: 6, title: "Data Structures: Lists", pages: ["Page 1: Creating lists", "Page 2: Indexing", "Page 3: Slicing", "Page 4: Methods", "Page 5: List comprehension", "Page 6: Nested lists"], quiz: "How to add item?", assignment: "Create a list of fruits" },
  { id: 7, title: "Tuples & Sets", pages: ["Page 1: Tuple creation", "Page 2: Immutability", "Page 3: Sets intro", "Page 4: Set uniqueness", "Page 5: Set operations", "Page 6: When to use which"], quiz: "Can you change tuples?", assignment: "Perform set union" },
  { id: 8, title: "Dictionaries", pages: ["Page 1: Key-value pairs", "Page 2: Accessing data", "Page 3: Adding/Removing", "Page 4: Iterating", "Page 5: Nested dicts", "Page 6: Dict methods"], quiz: "How to access keys?", assignment: "Contact book app" },
  { id: 9, title: "Functions", pages: ["Page 1: Defining functions", "Page 2: Parameters", "Page 3: Return values", "Page 4: Scope", "Page 5: Default args", "Page 6: Lambda functions"], quiz: "What is a lambda?", assignment: "Add two numbers using function" },
  { id: 10, title: "Modules & Packages", pages: ["Page 1: Imports", "Page 2: Built-in modules", "Page 3: Creating modules", "Page 4: Pip install", "Page 5: Virtual Envs", "Page 6: __name__ == '__main__'"], quiz: "How to import?", assignment: "Use 'math' module" },
  { id: 11, title: "File Handling", pages: ["Page 1: Opening files", "Page 2: Reading", "Page 3: Writing", "Page 4: Closing", "Page 5: Context Managers", "Page 6: File modes"], quiz: "What is 'w' mode?", assignment: "Write to a .txt file" },
  { id: 12, title: "Exception Handling", pages: ["Page 1: Try/Except", "Page 2: Finally", "Page 3: Raising errors", "Page 4: Custom exceptions", "Page 5: Error types", "Page 6: Best practices"], quiz: "How to catch errors?", assignment: "Handle ZeroDivisionError" },
  { id: 13, title: "OOP: Classes & Objects", pages: ["Page 1: Class concept", "Page 2: Attributes", "Page 3: Methods", "Page 4: The __init__", "Page 5: 'self' keyword", "Page 6: Instances"], quiz: "What is 'self'?", assignment: "Create 'Dog' class" },
  { id: 14, title: "Inheritance", pages: ["Page 1: Base classes", "Page 2: Derived classes", "Page 3: Super function", "Page 4: Multiple inheritance", "Page 5: Overriding", "Page 6: MRO"], quiz: "What is super()?", assignment: "Animal hierarchy" },
  { id: 15, title: "Polymorphism", pages: ["Page 1: Concept", "Page 2: Function overloading", "Page 3: Method overriding", "Page 4: Duck typing", "Page 5: Operator overloading", "Page 6: Interface logic"], quiz: "What is duck typing?", assignment: "Shape area calculator" },
  { id: 16, title: "Encapsulation & Abstraction", pages: ["Page 1: Private members", "Page 2: Public members", "Page 3: Getters/Setters", "Page 4: Abstract classes", "Page 5: Interfaces", "Page 6: Information hiding"], quiz: "What is a getter?", assignment: "Bank account privacy" },
  { id: 17, title: "Final Projects", pages: ["Page 1: Project planning", "Page 2: Git basics", "Page 3: Debugging", "Page 4: Deployment", "Page 5: Clean code", "Page 6: Portfolio"], quiz: "What is Git?", assignment: "Build a mini-game" }
];