-- Course content moves out of the frontend bundle and into the database, plus
-- the engagement features: resources, attendance, notifications.
--
-- Until now units and chapters lived in src/data/unitdata.js, so an admin
-- could not change a single word without a redeploy. They are tables now.

-- ==========================================================  units + chapters
CREATE TABLE IF NOT EXISTS public.units (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                    TEXT NOT NULL,
  difficulty               TEXT NOT NULL DEFAULT 'Beginner'
                             CHECK (difficulty IN ('Beginner', 'Intermediate', 'Advanced')),
  duration                 TEXT,
  position                 INTEGER NOT NULL DEFAULT 0,
  is_free                  BOOLEAN NOT NULL DEFAULT FALSE,
  is_published             BOOLEAN NOT NULL DEFAULT TRUE,
  assignment_title         TEXT,
  assignment_deadline_days INTEGER,
  assignment_points        INTEGER,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS units_position_idx ON public.units (position, id);

CREATE TABLE IF NOT EXISTS public.chapters (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id    INTEGER NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  position   INTEGER NOT NULL,
  title      TEXT NOT NULL,
  content    TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (unit_id, position)
);
CREATE INDEX IF NOT EXISTS chapters_unit_idx ON public.chapters (unit_id, position);

-- ================================================================= resources
-- Notes, PDFs, cheat sheets and external links attached to a unit.
CREATE TABLE IF NOT EXISTS public.resources (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id     INTEGER NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT,
  kind        TEXT NOT NULL DEFAULT 'file' CHECK (kind IN ('file', 'link')),
  url         TEXT NOT NULL,
  storage_key TEXT,
  mime_type   TEXT,
  size_bytes  BIGINT,
  position    INTEGER NOT NULL DEFAULT 0,
  created_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS resources_unit_idx ON public.resources (unit_id, position);

-- ================================================================ attendance
-- One row per student per day they actually studied. `day` is a date so the
-- primary key makes repeat visits idempotent.
CREATE TABLE IF NOT EXISTS public.attendance (
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  day           DATE NOT NULL DEFAULT CURRENT_DATE,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  visits        INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, day)
);
CREATE INDEX IF NOT EXISTS attendance_day_idx ON public.attendance (day DESC);

-- Called by the app on load. SECURITY DEFINER so a student can only ever
-- stamp their own attendance, never anybody else's.
CREATE OR REPLACE FUNCTION public.mark_attendance()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN; END IF;
  INSERT INTO public.attendance (user_id, day)
  VALUES (auth.uid(), CURRENT_DATE)
  ON CONFLICT (user_id, day) DO UPDATE
    SET last_seen_at = now(),
        visits       = public.attendance.visits + 1;
END;
$$;

-- ============================================================= notifications
-- user_id NULL means "everyone" - one row instead of a fan-out per student.
CREATE TABLE IF NOT EXISTS public.notifications (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL DEFAULT '',
  level      TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('info', 'success', 'warning')),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notifications_feed_idx ON public.notifications (created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_user_idx ON public.notifications (user_id, created_at DESC);

-- Read state is per user, so a broadcast can be read by one student and not
-- another without duplicating the message.
CREATE TABLE IF NOT EXISTS public.notification_reads (
  notification_id UUID NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  read_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (notification_id, user_id)
);

-- ======================================================================= RLS
ALTER TABLE public.units              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chapters           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------------------------------- units
-- Unit metadata (title, difficulty, whether it is free) is catalogue data:
-- the marketing pages show it to signed-out visitors. Chapter *content* is
-- what the paywall protects.
DROP POLICY IF EXISTS units_read ON public.units;
CREATE POLICY units_read ON public.units
  FOR SELECT TO anon, authenticated
  USING (is_published OR public.is_admin());

DROP POLICY IF EXISTS units_admin_write ON public.units;
CREATE POLICY units_admin_write ON public.units
  FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ------------------------------------------------------------------ chapters
DROP POLICY IF EXISTS chapters_read ON public.chapters;
CREATE POLICY chapters_read ON public.chapters
  FOR SELECT TO anon, authenticated
  USING (
    public.is_admin()
    OR public.has_course_access()
    OR EXISTS (SELECT 1 FROM public.units u WHERE u.id = unit_id AND u.is_free)
  );

DROP POLICY IF EXISTS chapters_admin_write ON public.chapters;
CREATE POLICY chapters_admin_write ON public.chapters
  FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ----------------------------------------------------------------- resources
DROP POLICY IF EXISTS resources_read ON public.resources;
CREATE POLICY resources_read ON public.resources
  FOR SELECT TO anon, authenticated
  USING (
    public.is_admin()
    OR public.has_course_access()
    OR EXISTS (SELECT 1 FROM public.units u WHERE u.id = unit_id AND u.is_free)
  );

DROP POLICY IF EXISTS resources_admin_write ON public.resources;
CREATE POLICY resources_admin_write ON public.resources
  FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------------- attendance
DROP POLICY IF EXISTS attendance_own ON public.attendance;
CREATE POLICY attendance_own ON public.attendance
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_admin());

-- ------------------------------------------------------------- notifications
DROP POLICY IF EXISTS notifications_read ON public.notifications;
CREATE POLICY notifications_read ON public.notifications
  FOR SELECT TO authenticated
  USING (user_id IS NULL OR user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS notifications_admin_write ON public.notifications;
CREATE POLICY notifications_admin_write ON public.notifications
  FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS notification_reads_own ON public.notification_reads;
CREATE POLICY notification_reads_own ON public.notification_reads
  FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- ==================================================================== grants
GRANT SELECT ON public.units, public.chapters, public.resources TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.units, public.chapters, public.resources TO authenticated;
GRANT SELECT ON public.attendance TO authenticated;
GRANT SELECT ON public.notifications TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.notifications TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notification_reads TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_attendance() TO authenticated;

-- ====================================================================== seed
-- Seeded from the original src/data/unitdata.js so no content is lost.
INSERT INTO public.units (id, title, difficulty, duration, position, is_free, assignment_title, assignment_deadline_days, assignment_points) VALUES
  (1, 'Introduction to Python', 'Beginner', '4 hours', 1, TRUE, 'Introduction to Python - practice set', 7, 10),
  (2, 'Variables, Data Types and Operations', 'Beginner', '5 hours', 2, FALSE, 'Variables, Data Types and Operations - practice set', 7, 10),
  (3, 'Control Flow - Conditional Statements', 'Beginner', '4 hours', 3, FALSE, 'Control Flow - Conditional Statements - practice set', 7, 10),
  (4, 'Loops - for and while', 'Beginner', '5 hours', 4, FALSE, 'Loops - for and while - practice set', 7, 10),
  (5, 'Functions and Scope', 'Beginner', '6 hours', 5, FALSE, 'Functions and Scope - practice set', 7, 10),
  (6, 'Lists and List Operations', 'Beginner', '5 hours', 6, FALSE, 'Lists and List Operations - practice set', 7, 10),
  (7, 'Tuples, Sets and Dictionaries', 'Beginner', '5 hours', 7, FALSE, 'Tuples, Sets and Dictionaries - practice set', 7, 10),
  (8, 'Working with Strings', 'Beginner', '4 hours', 8, FALSE, 'Working with Strings - practice set', 7, 10),
  (9, 'File I/O and Exception Handling', 'Intermediate', '6 hours', 9, FALSE, 'File I/O and Exception Handling - practice set', 7, 10),
  (10, 'Introduction to OOP', 'Intermediate', '6 hours', 10, FALSE, 'Introduction to OOP - practice set', 7, 10),
  (11, 'Inheritance and Polymorphism', 'Intermediate', '5 hours', 11, FALSE, 'Inheritance and Polymorphism - practice set', 7, 10),
  (12, 'Encapsulation and Abstraction', 'Intermediate', '4 hours', 12, FALSE, 'Encapsulation and Abstraction - practice set', 7, 10),
  (13, 'Modules and Packages', 'Intermediate', '4 hours', 13, FALSE, 'Modules and Packages - practice set', 7, 10),
  (14, 'Working with Libraries', 'Advanced', '6 hours', 14, FALSE, 'Working with Libraries - practice set', 7, 10),
  (15, 'Web Development Basics', 'Advanced', '7 hours', 15, FALSE, 'Web Development Basics - practice set', 7, 10),
  (16, 'Database Concepts and SQL', 'Advanced', '7 hours', 16, FALSE, 'Database Concepts and SQL - practice set', 7, 10),
  (17, 'Capstone and Professional Development', 'Advanced', '8 hours', 17, FALSE, 'Capstone and Professional Development - practice set', 7, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.chapters (unit_id, position, title, content) VALUES
  (1, 1, 'Overview', 'Python is a high-level, interpreted language designed around readability. You will install it, run your first script, and understand what the interpreter actually does.'),
  (1, 2, 'In practice', 'Work through the examples for "Introduction to Python" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (1, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (2, 1, 'Overview', 'Names bind to objects. Learn int, float, str, bool, how Python infers types, and how arithmetic and comparison operators behave.'),
  (2, 2, 'In practice', 'Work through the examples for "Variables, Data Types and Operations" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (2, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (3, 1, 'Overview', 'if / elif / else, truthiness, and how indentation - not braces - defines a block in Python.'),
  (3, 2, 'In practice', 'Work through the examples for "Control Flow - Conditional Statements" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (3, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (4, 1, 'Overview', 'Iterate over sequences with for, repeat on a condition with while, and control both with break, continue and else.'),
  (4, 2, 'In practice', 'Work through the examples for "Loops - for and while" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (4, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (5, 1, 'Overview', 'Define reusable behaviour, pass arguments positionally and by keyword, return values, and understand local vs global scope.'),
  (5, 2, 'In practice', 'Work through the examples for "Functions and Scope" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (5, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (6, 1, 'Overview', 'Ordered, mutable sequences: indexing, slicing, appending, sorting, and list comprehensions.'),
  (6, 2, 'In practice', 'Work through the examples for "Lists and List Operations" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (6, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (7, 1, 'Overview', 'Immutable tuples, unique-membership sets, and key/value dictionaries - and when each is the right choice.'),
  (7, 2, 'In practice', 'Work through the examples for "Tuples, Sets and Dictionaries" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (7, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (8, 1, 'Overview', 'Strings are immutable sequences. Slicing, f-strings, split/join, and the methods you will reach for daily.'),
  (8, 2, 'In practice', 'Work through the examples for "Working with Strings" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (8, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (9, 1, 'Overview', 'Read and write files with context managers, and handle failure with try / except / finally instead of crashing.'),
  (9, 2, 'In practice', 'Work through the examples for "File I/O and Exception Handling" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (9, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (10, 1, 'Overview', 'Classes bundle data and behaviour. Learn __init__, instance attributes, and methods.'),
  (10, 2, 'In practice', 'Work through the examples for "Introduction to OOP" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (10, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (11, 1, 'Overview', 'Reuse behaviour across classes, override methods, and let one interface serve many types.'),
  (11, 2, 'In practice', 'Work through the examples for "Inheritance and Polymorphism" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (11, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (12, 1, 'Overview', 'Hide internal state behind a stable interface using properties and naming conventions.'),
  (12, 2, 'In practice', 'Work through the examples for "Encapsulation and Abstraction" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (12, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (13, 1, 'Overview', 'Split code across files, import it, and understand what __name__ == ''__main__'' is doing.'),
  (13, 2, 'In practice', 'Work through the examples for "Modules and Packages" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (13, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (14, 1, 'Overview', 'pip, virtual environments, and the standard-library modules worth knowing before reaching for a dependency.'),
  (14, 2, 'In practice', 'Work through the examples for "Working with Libraries" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (14, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (15, 1, 'Overview', 'HTTP, requests and responses, and serving a first small web application from Python.'),
  (15, 2, 'In practice', 'Work through the examples for "Web Development Basics" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (15, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (16, 1, 'Overview', 'Tables, keys, joins, and querying a relational database from Python.'),
  (16, 2, 'In practice', 'Work through the examples for "Database Concepts and SQL" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (16, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.'),
  (17, 1, 'Overview', 'Combine everything into one project, put it under version control, and write a README somebody else can follow.'),
  (17, 2, 'In practice', 'Work through the examples for "Capstone and Professional Development" in your own editor. Type every snippet by hand - reading code is not the same as writing it.'),
  (17, 3, 'Common mistakes', 'Re-read the error messages you hit. Most beginner bugs in this unit come from assuming the code did what you meant rather than what you wrote.')
ON CONFLICT (unit_id, position) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.units','id'), (SELECT MAX(id) FROM public.units));

-- ============================================ single source of truth for free
-- is_free_unit() used to hardcode "unit 1". It now reads public.units, so an
-- admin ticking "free" in the dashboard changes every gate at once - chapter
-- text, videos, resources and the quiz function.
--
-- The volatility changes (IMMUTABLE -> STABLE), so the function has to be
-- dropped and rebuilt; the policy that depends on it is rebuilt with it.
DROP POLICY IF EXISTS unit_videos_read ON public.unit_videos;
DROP FUNCTION IF EXISTS public.is_free_unit(INTEGER);

CREATE FUNCTION public.is_free_unit(p_unit_id INTEGER)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.units WHERE id = p_unit_id AND is_free
  );
$$;

CREATE POLICY unit_videos_read ON public.unit_videos
  FOR SELECT TO authenticated, anon
  USING (
    public.is_free_unit(unit_id)
    OR public.has_course_access()
    OR public.is_admin()
  );

-- Keep the videos table pointing at real units now that they exist.
ALTER TABLE public.unit_videos DROP CONSTRAINT IF EXISTS unit_videos_unit_id_check;
